# Generated by Django 3.2.8 on 2021-10-16 16:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('inscricao', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1)),
                ('idade', models.IntegerField()),
                ('cor', models.IntegerField(choices=[(0, 'Não declarado'), (1, 'Branca'), (2, 'Preta'), (3, 'Parda'), (4, 'Amarela'), (5, 'Indígena')])),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codMunicipio', models.AutoField(primary_key=True, serialize=False)),
                ('nomeMunicipio', models.CharField(max_length=200)),
                ('siglaUf', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('idProva', models.AutoField(primary_key=True, serialize=False)),
                ('corNatureza', models.IntegerField(blank=True, choices=[(1, 'Azul'), (2, 'Amarela'), (3, 'Branca'), (4, 'Rosa'), (5, 'Laranja - Adaptada Ledor'), (6, 'Verde - Videoprova - Libras'), (7, 'Azul (Reaplicação)'), (8, 'Amarela (Reaplicação)'), (9, 'Branco (Reaplicação)'), (10, 'Rosa (Reaplicação)'), (11, 'Laranja - Adaptada Ledor (Reaplicação)'), (12, 'Cinza'), (13, 'Cinza (Reaplicação)')], null=True)),
                ('corHumanas', models.IntegerField(blank=True, choices=[(1, 'Azul'), (2, 'Amarela'), (3, 'Branca'), (4, 'Rosa'), (5, 'Laranja - Adaptada Ledor'), (6, 'Verde - Videoprova - Libras'), (7, 'Azul (Reaplicação)'), (8, 'Amarela (Reaplicação)'), (9, 'Branco (Reaplicação)'), (10, 'Rosa (Reaplicação)'), (11, 'Laranja - Adaptada Ledor (Reaplicação)'), (12, 'Cinza'), (13, 'Cinza (Reaplicação)')], null=True)),
                ('corLinguagem', models.IntegerField(blank=True, choices=[(1, 'Azul'), (2, 'Amarela'), (3, 'Branca'), (4, 'Rosa'), (5, 'Laranja - Adaptada Ledor'), (6, 'Verde - Videoprova - Libras'), (7, 'Azul (Reaplicação)'), (8, 'Amarela (Reaplicação)'), (9, 'Branco (Reaplicação)'), (10, 'Rosa (Reaplicação)'), (11, 'Laranja - Adaptada Ledor (Reaplicação)'), (12, 'Cinza'), (13, 'Cinza (Reaplicação)')], null=True)),
                ('corMatematica', models.IntegerField(blank=True, choices=[(1, 'Azul'), (2, 'Amarela'), (3, 'Branca'), (4, 'Rosa'), (5, 'Laranja - Adaptada Ledor'), (6, 'Verde - Videoprova - Libras'), (7, 'Azul (Reaplicação)'), (8, 'Amarela (Reaplicação)'), (9, 'Branco (Reaplicação)'), (10, 'Rosa (Reaplicação)'), (11, 'Laranja - Adaptada Ledor (Reaplicação)'), (12, 'Cinza'), (13, 'Cinza (Reaplicação)')], null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('idResultado', models.AutoField(primary_key=True, serialize=False)),
                ('statusRedacao', models.IntegerField(blank=True, choices=[(1, 'Sem problemas'), (2, 'Anulada'), (3, 'Cópia Texto Motivador'), (4, 'Em Branco'), (6, 'Fuga ao tema'), (7, 'Não atendimento ao tipo textual'), (8, 'Texto insuficiente'), (9, 'Parte desconectada')], null=True)),
                ('notaNatureza', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('notaHumanas', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('notaMatematica', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('notaLinguagem', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('notaRedacao', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('treineiro', models.IntegerField(blank=True, choices=[(1, 'Sim'), (0, 'Não')], null=True)),
                ('idProva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='enem.prova')),
                ('inscricaoCandidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='enem.candidato')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='codMunicipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='enem.municipio'),
        ),
    ]
