# Generated by Django 3.2.8 on 2021-10-15 01:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('inscricao', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('sexo', models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMININO')], max_length=1)),
                ('idade', models.IntegerField()),
                ('cor', models.IntegerField(choices=[(0, 'Não declarado'), (1, 'Branca'), (2, 'Preta'), (3, 'Parda'), (4, 'Amarela'), (5, 'Indígena')])),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('codMunicipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nomeMunicipio', models.CharField(max_length=200)),
                ('siglaUf', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Prova',
            fields=[
                ('idProva', models.IntegerField(primary_key=True, serialize=False)),
                ('corCiencias', models.IntegerField(choices=[(507, 'Azul'), (508, 'Amarela'), (509, 'Branca'), (510, 'Rosa'), (520, 'Laranja - Adaptada Ledor'), (524, 'Verde - Videoprova - Libras'), (547, 'Azul (Reaplicação)'), (548, 'Amarelo (Reaplicação)'), (549, 'Branco (Reaplicação)'), (550, 'Rosa (Reaplicação)'), (564, 'Laranja - Adaptada Ledor (Reaplicação)')])),
                ('corMatematica', models.IntegerField(choices=[(507, 'Azul'), (508, 'Amarela'), (509, 'Branca'), (510, 'Rosa'), (520, 'Laranja - Adaptada Ledor'), (524, 'Verde - Videoprova - Libras'), (547, 'Azul (Reaplicação)'), (548, 'Amarelo (Reaplicação)'), (549, 'Branco (Reaplicação)'), (550, 'Rosa (Reaplicação)'), (564, 'Laranja - Adaptada Ledor (Reaplicação)')])),
                ('corHumanas', models.IntegerField(choices=[(507, 'Azul'), (508, 'Amarela'), (509, 'Branca'), (510, 'Rosa'), (520, 'Laranja - Adaptada Ledor'), (524, 'Verde - Videoprova - Libras'), (547, 'Azul (Reaplicação)'), (548, 'Amarelo (Reaplicação)'), (549, 'Branco (Reaplicação)'), (550, 'Rosa (Reaplicação)'), (564, 'Laranja - Adaptada Ledor (Reaplicação)')])),
                ('corLinguagem', models.IntegerField(choices=[(507, 'Azul'), (508, 'Amarela'), (509, 'Branca'), (510, 'Rosa'), (520, 'Laranja - Adaptada Ledor'), (524, 'Verde - Videoprova - Libras'), (547, 'Azul (Reaplicação)'), (548, 'Amarelo (Reaplicação)'), (549, 'Branco (Reaplicação)'), (550, 'Rosa (Reaplicação)'), (564, 'Laranja - Adaptada Ledor (Reaplicação)')])),
            ],
        ),
        migrations.CreateModel(
            name='Realiza',
            fields=[
                ('idResultado', models.IntegerField(primary_key=True, serialize=False)),
                ('statusRedacao', models.IntegerField(choices=[(1, 'Sem problemas'), (2, 'Anulada'), (3, 'Cópia Texto Motivador'), (4, 'Em Branco'), (6, 'Fuga ao tema'), (7, 'Não atendimento ao tipo textual'), (8, 'Texto insuficiente'), (9, 'Parte desconectada')])),
                ('notaCiencias', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('notaMatematica', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('notaHumanas', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('notaLinguagem', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('notaRedacao', models.DecimalField(decimal_places=1, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)])),
                ('treineiro', models.IntegerField(choices=[(1, 'Sim'), (0, 'Não')])),
                ('idProva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='enem.prova')),
                ('inscricaoCandidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='realizacoes', to='enem.candidato')),
            ],
        ),
        migrations.AddField(
            model_name='candidato',
            name='codMunicipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='enem.municipio'),
        ),
    ]
