# Generated by Django 3.2.8 on 2021-10-15 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enem', '0002_alter_prova_idprova'),
    ]

    operations = [
        migrations.RenameField(
            model_name='prova',
            old_name='corCiencias',
            new_name='corNatureza',
        ),
    ]
