# Generated by Django 3.2.8 on 2021-10-15 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enem', '0003_rename_corciencias_prova_cornatureza'),
    ]

    operations = [
        migrations.RenameField(
            model_name='realiza',
            old_name='notaCiencias',
            new_name='notaNatureza',
        ),
        migrations.AlterField(
            model_name='municipio',
            name='codMunicipio',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
