# Generated by Django 3.2.8 on 2021-10-15 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enem', '0004_auto_20211015_0228'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realiza',
            name='idResultado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
