version: "3.9"

services:

  db:
    container_name: mysql
    image: mysql:latest
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: enem
      MYSQL_USER: adminadmmin
      MYSQL_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
    ports:
      - '3306:3306'
    volumes:
      - ./dump.sql:/dump.sql
      - var_lib_mysql:/var/lib/mysql
      - ./my.cnf:/etc/my.cnf
      - docker_entrypoint_initdb_d:/docker-entrypoint-initdb.d
    networks:
      - app-network

    deploy:
      resources:
        limits:
          cpus: '3'
          memory: 8192M

  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command:  ["./gunicorn_start.sh"]
    ports:
      - 8000:8000 # server port
      - 8001:8001 # debug port
    volumes:
      - ./src:/src
      - pip_cache:/usr/local/lib/python3/site-packages
    networks:
      - app-network

networks:
  app-network:
    name: app-network
    driver: bridge

volumes:
  pip_cache:
  var_lib_mysql:
  etc_mysql_confd_my_cnf:
  docker_entrypoint_initdb_d:
