# Generated by Django 3.2.8 on 2021-10-28 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='realiza',
            name='idResultado',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
