# Generated by Django 3.2.8 on 2021-10-21 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enem', '0002_auto_20211021_1307'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='candidato',
            table='CANDIDATO',
        ),
        migrations.AlterModelTable(
            name='municipio',
            table='MUNICIPIO',
        ),
        migrations.AlterModelTable(
            name='prova',
            table='PROVA',
        ),
        migrations.AlterModelTable(
            name='realiza',
            table='realiza',
        ),
    ]
